### ISSUE TITLE
请求flask编写的服务器的api的时候，会报"Failed to decode JSON object: No JSON object could be decoded"错误

### ISSUE THREAD

**Issue by slin60** [hatedMe/wechat-request#2]
{message: "Failed to decode JSON object: No JSON object could be decoded"}
不管把头信息设置成
    wxRequest.defaults.headers.get['content-Type'] = 'application/x-www-form-urlencoded'
还是
   wxRequest.defaults.headers.get['Content-Type'] = 'application/json'

都是一样的返回400错误：
data:
message:
"Failed to decode JSON object: No JSON object could be decoded"
__proto__:Object
headers:
{Content-Type: "application/json", Content-Length: "83", Server: "Werkzeug/0.14.1 Python/2.7.14", Date: "Wed, 25 Apr 2018 07:39:50 GMT"}

我用浏览器直接请求或者用内置的wx.request（把content-type信息设置成application/x-www-form-urlencoded）则不会报这个错，不知道什么原因。

**Comment by hatedMe** [comment]
感谢你的使用，并感谢你提出的问题。`1.4.0 `已经修复。
