### ISSUE TITLE
wxRequest.post不起作用。

### ISSUE THREAD

**Issue by slin60** [hatedMe/wechat-request#3]
使用wxRequest.post进行请求时，每次都很快就返回操作成功的提示。但是返回的信息的data为null，同时查看服务器显示该请求并没有执行。
{data: null, headers: {…}, status: 200, statusText: "ok"}
data:null
headers:{Content-Type: "application/json", Content-Length: "5", Server: "Werkzeug/0.14.1 Python/3.6.5", Date: "Sat, 28 Apr 2018 12:44:13 GMT"}
status:200
statusText:"ok"

使用浏览器或者自带函数进行相同的操作则没有这个问题。恳请解答下这是怎么回事呢？

**Comment by hatedMe** [comment]
感谢你的使用，并感谢你提出的问题。加班加点深入定位问题已经在`1.4.1`中修复。

**Comment by slin60** [comment]
非常感谢！

**Comment by slin60** [comment]
还有个小问题，我设置默认的AUTH_TOKEN该怎么操作呢？

wxRequest.defaults.headers.common['Authorization'] = AUTH_TOKEN这样的语句好像在微信开发工具里边要提示报错。
