### ISSUE TITLE
您好，支持multipart/form-data吗？

### ISSUE THREAD

**Issue by cb360** [hatedMe/wechat-request#6]
小程序默认的upload不能传多个字段的file文件，也不支持patch等方法
请问你这个库支持multipart/form-data吗？我没有看到相关说明。

**Comment by hatedMe** [comment]
此包是针对微信小程序 API wx.request 发起 HTTPS 网络请求的封装。
https://developers.weixin.qq.com/miniprogram/dev/api/wx.request.html

**Comment by cb360** [comment]
好的，明白了，谢谢！
